name: Test Self Hosted Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Show hostname
        run: hostname

      - name: Show current user
        run: whoami

      - name: Check Kubernetes
        run: kubectl get nodes
